## one-shot prompt for the cluster

cluster_system_prompt = "You are Qwen, created by Alibaba Cloud. You are a helpful assistant.You need to judge if two steps in a math solution get the same conclusion. You will be given the math problem, the first x steps to solve it, and two possibilities of the next step. Your task is to judge if they are the same. Format your response as one single word: Same/Different. Do not say anything else.\n"

extract_system_prompt = "You are Qwen, created by Alibaba Cloud. You are a helpful assistant. You will be given one step within a step-by-step solution of some math problem. You need to extract the key conclusion of the step and make it simple. Do not say anything else.\n"

# cluster_system_response = "Got it!"
cluster_user_prompt = "Question: A merchant wants to make a choice of purchase between 2 purchase plans: jewelry worth $5,000 or electronic gadgets worth $8,000. His financial advisor speculates that the jewelry market will go up 2.5% while the electronic gadgets market will rise 1.2% within the same month. If the merchant is looking to maximize profit at the end of this month by making a choice, how much profit would this be?\n\nStep-by-Step Solution: \n**Step 1**: Calculate the profit if the merchant purchases jewelry. Profit = $5,000 * 2.5% = $125.\n**Step 2**: Calculate the profit if the merchant purchases electronic gadgets. Profit = $8,000 * 1.2% = $96.\n\nPossibility 1: **Step 3**: $125 > $96, the merchant should purchase jewelry to maximize profit. The profit would be $125.\n\nPossibility 2: **Step 3**: $96 < $125, the merchant should purchase electronic gadgets to maximize profit. The profit would be $96.\n Do possibility 1, 2 get the same conclusion? Response: "
cluster_user_response = "Different.\n"

cluster_system_prompt2 = "You are Qwen, created by Alibaba Cloud. You are a helpful assistant. You will be given a math problem, the first x steps to solve it, and a list of possible next steps. Each possibility will be marked as **[1]**, **[2]**, **[3]**, etc. Your task is to cluster similar responses. For example, if **[1]** and **[3]** are the same, while **[2]** is different from them, you should format your response as: **[1, 3]**, **[2]**. You should make sure each given possibility is included one and only one cluster. Do not say anything else.\n"